### ISSUE TITLE
issue with make command

### ISSUE THREAD

**Issue by benkeser** [sabrishamcar/Data550_finalproject#2]
you have an issue with your make command, please review hints on canvas.

**Comment by sabrishamcar** [comment]
Thanks, I will check this. If this is regarding the hint you have reminded us about 3 times I did try to implement that but maybe I am still missing something.... would you be able to provide more information regarding the error you encountered? Thanks a lot!

**Comment by benkeser** [comment]
no, it wasn't that hint. here's the error:

<img width="1340" alt="Screen Shot 2024-05-02 at 12 11 20 PM" src="https://github.com/sabrishamcar/Data550_finalproject/assets/17482713/fe0f1373-1f9d-48de-8f70-1feef550da74">

**Comment by sabrishamcar** [comment]
Thank you!
